name:                simplex-model
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/simplex-model#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

# default-extensions:
  # - DataKinds
  # - DeriveAnyClass
  # - FlexibleInstances
  # - FunctionalDependencies
  # - InstanceSigs
  # - MultiParamTypeClasses
  # - NoMonomorphismRestriction
  # - OverloadedStrings
  # - RankNTypes
  # - TemplateHaskell
  # - TypeSynonymInstances

dependencies:
  - base >= 4.7 && < 5
  - containers
  - lens
  - mtl
  - transformers
  - simplex-definitions

library:
  source-dirs: src

executables:
  simplex-model:
    source-dirs:      src
    main:             Main.hs

tests:
  doctests:
    source-dirs: doctest
    main: doctest-driver.hs
    dependencies:
      - base
      - doctest
      - doctest-driver-gen
